In [1]:
tets

NameError: name 'tets' is not defined

In [2]:
# lskjdf;lskdf

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
pip install numpy


  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/82/0f/3f712cd84371636c5375d2dd70e7514d264cec6bdfc3d7997a4236e9f948/numpy-1.26.1-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 110.1 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 179.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 187.9 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 203.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [6]:
my_list = [1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
arr[:1]

array([1])

In [11]:
arr2 = arr[:1]

In [12]:
arr2

array([1])

In [14]:
arr3 = np.arange(2, 30)

In [15]:
arr3

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
arr3[2:9:2]

array([ 4,  6,  8, 10])